#Instala el servidor FTP en el directorio /var/spool/asterisk/monitor
version: '3.0'

services:
 ftpserver:
  image: "nsoporte/ftpserver"
  container_name: "ftpserver-nspbx"
  network_mode: "host"
  volumes:
   - "/etc/localtime:/etc/localtime:ro"
   - "/data/etc/ftpserver:/conf"
   - "/data/var/log/ftpserver:/log"
   - "/var/spool/asterisk/monitor:/ftp"