#Servicio de monitoreo para Nagios
version: '3.0'

services:
 nrpe:
  image: "nsoporte/nrpe:latest"
  container_name: "nrpe"
  network_mode: "host"
  privileged: "true"
  volumes:
   - "/etc/hostname:/etc/hostname:ro"
   - "/etc/localtime:/etc/localtime:ro"
   - "/proc:/host/proc"
   - "/:/host/disk/rootfs"
   - "/data:/host/disk/datafs"
   - "/data/etc/nrpe/custom:/custom"
   - "/data/etc/nrpe/plugins:/plugins"
   - "/var/run/utmp:/var/run/utmp:ro"
   - "/var/run/docker.sock:/var/run/docker.sock"